# Data
data_root: "./data/BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData"
input_modalities: ["flair", "t1ce"]
val_split: 0.15
test_split: 0.15

# Model / training
img_size: 128
volume_slices: 100
volume_start_at: 22
cache_size: 6
epochs: 40
batch_size: 64
num_workers: 16
lr: 0.0002
weight_decay: 0.0001
alpha: 0.5
beta: 0.5
dropout: 0.35

# Runtime
seed: 42
device: auto
output_root: "Output"
lr_patience: 5
lr_min: 0.000001
